export * from './Kanto';
export * from './Johto';
export * from './Hoenn';
export * from './Sinnoh';
export * from './Unova';
export * from './Kalos';
export * from './Alola';
export * from './Galar';
export * from './Home';
